apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fooserver
  name: fooserver
spec:
  containers:
  - image: kingzim/hiserver
    name: fooserver
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
