apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  containers:
    - image: nginx:1.14
      name: nginx-container
      ports:
      - containerPort: 80
    - image: ubuntu:22.04
      name: ubuntu-container
      command:
      - sleep
      - "10000"

