namespace: prod
resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml

images:
  - name: gcr.io/heptio-images/ks-guestbook-demo
    newTag: "0.1"

namePrefix: prod-

patches:
  - target:
      kind: Service
      name: prod-guestbook1
    path: service-patch.yaml