FROM python:3
RUN apt-get update && apt-get upgrade && apt-get install -y vim nginx
WORKDIR /code
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html /var/www/html/index.html
COPY custom-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/custom-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/custom-entrypoint.sh"]
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]